### ISSUE TITLE
show coordinates with fixed fraction

### ISSUE THREAD

**Issue by derFrickler** [zapmaker/GrblHoming#1]
Hi zapmaker,

Just found your GrblHoming tool and i must say that it is great!
Runs much faster on my raspberry than the UniversalGcodeSender i used before, and all Buttons/Controls are just the way i wished them to be. 

Just one small thing to be improved.
I would display the coordinates with a fixed fraction of 3 digits, right now the display of the values is flickering quite much while running, as some values are displayed with one digit and others with 4 or 5. e.g. 4 / 4.121. That makes it a bit hard to read the values while changing.

btw. here is my website with the doc. about my eShapeOko and my FräsberryPI
http://der-frickler.net/technik/frickelfraese#der_fraesberry_pi

Greets
     Johannes

**Comment by zapmaker** [comment]
Yes, I agree and it needs to be fixed. I will add it to the list of items to fix in the next release.

Nice work on the eshapeoko. Thanks for the link (I can read some German, so that makes it more fun).

**Comment by zapmaker** [comment]
Fixed in 3.3.6

**Comment by derFrickler** [comment]
Very nice, 
so my poor raspberry will have to compile again this evening  ;_)

**Comment by derFrickler** [comment]
Compiles in about 30minuts and works fine on my raspberry!
