### ISSUE TITLE
Be reminded to do zero position right before begin button if not at zero

### ISSUE THREAD

**Issue by zapmaker** [zapmaker/GrblHoming#10]
It is annoying to have forgotten to click the zero position button right after starting a job. Find some way to make it easier, i.e. prompt user if work coordinates are not zeroed when begin button is pushed

**Comment by zapmaker** [comment]
Note - some workflows are to raise the Z before turning on the spindle, so that needs to be taken into account

**Comment by kosme** [comment]
Done. Would like to push it to the repository.

**Comment by zapmaker** [comment]
Fixed by kosme and in code 3.4.4
