### ISSUE TITLE
Z axis slider in inches mode should move in 0.1 inch increments, not inches

### ISSUE THREAD

**Issue by zapmaker** [zapmaker/GrblHoming#17]
In inches mode, the Z axis slider is too sensitive and not very useful - reduce step by 1/10

**Comment by kosme** [comment]
Created a fix but can't push it

**Comment by zapmaker** [comment]
Hi - I ran a test and a found a problem when switching back from inches to mm - i don't know if this was caused by your code change or already in the code, but now the current position is very large.

I test the UI with an arduino that is not connected to any hardware to make things easier.

steps: 
1. Started in inches mode
2. Use button z axis
3. Ran a job
4. Switch to mm mode in options
5. Used jog

Can you look? Thanks.

![largepos](https://f.cloud.github.com/assets/2454235/1016878/cc6839a2-0c03-11e3-8b55-4b190492476f.png)

**Comment by kosme** [comment]
Looks like the cast from int to double in mainwindow.cpp is generating an overflow. Just followed your steps and confirmed the error. Also discovered by that way that the slider affects the dials and the number with the overflow but the Z axis buttons only affect the dials.

**Comment by zapmaker** [comment]
ok, thanks. I will be looking at this and then also incorporating letartares changes.

**Comment by kosme** [comment]
Already working on a fix

**Comment by zapmaker** [comment]
Fixed by kosme and incorporated into 3.4.4
