### ISSUE TITLE
Get the latest manual controls

### ISSUE THREAD

**Issue by LETARTARE** [zapmaker/GrblHoming#26]
hello,
first of all, a VERY VERY big thank you for this software.
I propose to replace :
'QLineEdit \* Command'  ->   'QComboBox \* Command->lineEdit()'
allowing to recover one of the last commands entered.

I tested this change on the latest version r64, it works fine (VISTA pro SP2).

Sincerely.

rem: the text is translated by google

**Comment by zapmaker** [comment]
I will put this into the next version. Thanks.

**Comment by zapmaker** [comment]
Merged into 3.4.4
