### ISSUE TITLE
Incorrect units

### ISSUE THREAD

**Issue by kosme** [zapmaker/GrblHoming#27]
When connecting to the arduino, if the work units are inches, the dials display the equivalent in mm.
![bug](https://f.cloud.github.com/assets/1418331/927144/6b6944d6-ff9a-11e2-9fc1-5c74b80da8d6.JPG)

**Comment by zapmaker** [comment]
I have seen this as an issue also. Thanks. Are you the original author of the program?

**Comment by kosme** [comment]
Yes, I am.

**Comment by zapmaker** [comment]
merged into 3.4.4
