### ISSUE TITLE
Update 4 axes and translation

### ISSUE THREAD

**Issue by LETARTARE** [zapmaker/GrblHoming#29]
I propose an adaptation to a Mega2560 card that manages four axes using
https://github.com/EliteEng/grbl.git
Card driving axis C. :
![grbl081_mega2560](https://f.cloud.github.com/assets/5158475/939315/f579aa8e-0112-11e3-9569-2a92a70e7deb.jpg)
The adaptation of software :
![4axis_en](https://f.cloud.github.com/assets/5158475/939336/5e6b6b40-0113-11e3-9377-264ad83ad21e.jpg)
Settings :
![settings_en](https://f.cloud.github.com/assets/5158475/939358/b6d37232-0113-11e3-9602-7191aec47818.jpg)

And its translation into French:
![4axis_fr](https://f.cloud.github.com/assets/5158475/939347/87c3023c-0113-11e3-9d07-e7f15fe0e95b.jpg)

Some features need to be adapted ($X, Open/Close, ...)
What do you think?

**Comment by zapmaker** [comment]
I really like this idea of a four axis view. Do you think it is much work to make it dynamic (via an option checkbox?) I am also interested in figuring out how to localize the code (i.e. offer language support).

If I open the code to you as a contributor, you could create a git branch and put your code in there and check it in - are you up for that?

**Comment by LETARTARE** [comment]
1- For dynamic detection, I'll look, I think the fastest would be a button box (3 or 4 axis) before connecting.
2- For the translation I can send you the modified source, it is not very complicated. 
3- To contribute, I do not know anything about using git, on the other hand, I do not use makefile to compile.
I added  to 'Code :: Blocks 12.11 a plugin script to build projects Qt-4.7.1 and I created a project Code::Blocks' (ContoleurCnc4.cbp) which allows me to build the controller.
Also, before accepting your offer, I'll try again with a makefile and I will send you the result.
Cordially
rem: text is translated by google

**Comment by LETARTARE** [comment]
Here is the patch for 3.4.3  'cnc4axis.patch' (remove. jpg ! )
![cnc4axis 7z](https://f.cloud.github.com/assets/5158475/1009753/fcbee9dc-0b3d-11e3-8753-45f7e008a594.jpg)
I also modified the 3.4.4, this works well.

Is there another way to send you a 7z  ?

For translation
1- create directory "trlocale"
2- "lupdate.exe GcodeSenderGUIthreads.pro" -> "trlocale\controleurcnc4_fr.ts" 
3- edit this file with 'Qt Linguist', translate and save
4- "lrelease.exe trlocale/controleurcnc4_fr.qm" 
5-place this file with "GrblController.exe"

**Comment by zapmaker** [comment]
Merged into 3.4.4
