### ISSUE TITLE
delay between 2 short g01 commands.

### ISSUE THREAD

**Issue by derFrickler** [zapmaker/GrblHoming#3]
When i try to mill some figures with very short paths (lots of g01 commands in short time) then grbl shows some kind of sleep between the commands, meaning the moving axis stop for a short time before they go for the next G01 command. Looks like there is a delay between 2 commands that are sent to grbl - or maybe the sending is just to slow. 

The same problem does not occur with universalgcodesender on the same grbl/mill,  universalgcodesender fills up the command buffer of grbl fast enough i guess.

I am not shure if this may have come with your latest fix (delay to work with arduino nano and pro mini) , as this is the first time i really used GRBLController for milling, not only for dry runs on my arduino with grbl, but sithout steppers.

greets
       Johannes

**Comment by zapmaker** [comment]
Go to Tools > Options and check "use aggressive preload strategy for Grbl" and the pause will no longer be there. I will be changing the default to have this checked in the next version (3.4).
