### ISSUE TITLE
Automatic detection 3 or 4 axis with 3.4.4

### ISSUE THREAD

**Issue by LETARTARE** [zapmaker/GrblHoming#34]
Hello,
I managed to make an automatic detection in the first position returned.
It certainly remains adjustments, but I do not know enough about the code to do it.
How can I send you a compressed patch for 3.4.4 ?

![4axis_en](https://f.cloud.github.com/assets/5158475/1020727/e1342b50-0cbe-11e3-99b0-99a1c9203e7c.jpg)
![3axis_en](https://f.cloud.github.com/assets/5158475/1020728/1ad694c4-0cbf-11e3-8465-ea0cb2fec697.jpg)

-->  look at my first post on four axes ...
cordially

**Comment by zapmaker** [comment]
There are different ways to send me the patch. One way is to zip up your GrblHoming folder and email it to me. Mail me at zapmaker.org. My username is zapmaker.

Another way would involve me sending you steps to perform using git. Let me know if you want to do it via git.

**Comment by LETARTARE** [comment]
Yes, I want to do via Git.
But I will also try "zapmaker@zapmaker.org" 
I made a fork, then I made changes today , you can see ...

**Comment by zapmaker** [comment]
Fixed in 3.4.4
