### ISSUE TITLE
Serial Baudrate is Hardcoded

### ISSUE THREAD

**Issue by nicolas-lang** [zapmaker/GrblHoming#4]
the GRBL wiki ( https://github.com/grbl/grbl/wiki/Frequently-Asked-Questions ) states that the only reason for a baudrate of 9600 is to "minimize connection problems for the newbie." and it is part of the configuration, allowing users to increase it for faster reactions & better transfer.

Allowing to change it might also resolve the laggy response of the Jog buttons.

**Comment by zapmaker** [comment]
Yes, I have baud rate change scheduled for 3.4, thanks.

**Comment by zapmaker** [comment]
Fixed in 3.4. Standard baud rates from 9600 - 115200 now supported.
