### ISSUE TITLE
Valid G-code rejected

### ISSUE THREAD

**Issue by lakeside53** [zapmaker/GrblHoming#5]
I have the following  sequence  (fragment) :

G4 P0.15        (delay for stabilization)
M8          ( shutter release  - on, using  flood coolant control)
G4 P0.05        ( wait 50 msec)
M9          (shutter release - off) 
G4 P0.1     ( wait to tune camera performance to loop

The first  few time i ran the program all of the P0.xx are rejected.  I get 'removing unsupported command P0.xx'.  They are however quite valid and load with other g-code uploaders.

Then : 
I toggled  two the options : "aggressive preload strategy" and "filter file commands before sending".  The problem went away.   I turned  them back off... the problem did not occur.  I restarted    -still no problem.    Hmmmm...

I'm running 3.3.5
I'll dig a little deeper...

**Comment by zapmaker** [comment]
Fixed in 3.4. It was necessary to wait for the coolant off command (M9) ok response before sending further commands. This is due to grbl's modal treatment of certain commands.
