### ISSUE TITLE
G Code truncation error

### ISSUE THREAD

**Issue by pacaj2am** [zapmaker/GrblHoming#53]
Hello,

when sending G3 commands , there are truncation errors, see datil in shapeoko forum>

http://www.shapeoko.com/forum/viewtopic.php?f=3&t=3259&p=24569#p24569

**Comment by zapmaker** [comment]
thanks for posting, i'll take a look soon

**Comment by zapmaker** [comment]
Quick fix until I get a permanant fix in place: I checked the code and it is truncating to 50 characters, which is the buffer size, but unfortunately I didn't add the linefeed characters to the count, which is sent later, thus it overflows the buffer causing the error. One easy temporary solution is to change the Grbl Line Buffer Size in Tools | Options from 50 to 49, which should solve the problem. That changes Grbl Controller's expectations of grbl's buffer size - it doesn't change anything in grbl itself!

**Comment by zapmaker** [comment]
Fixed in 3.6 - subtracted 1 from the line buffer size when doing the calc
