### ISSUE TITLE
Axis C -> axis A 

### ISSUE THREAD

**Issue by LETARTARE** [zapmaker/GrblHoming#56]
hi Roman,
I move to amend the C axis (around Z) to  A (around X) which is more useful.

![grbl controller-351_a_eng](https://cloud.githubusercontent.com/assets/5158475/2740787/015d5c7c-c6db-11e3-9a57-7bcea4a7cafb.jpg)

![grbl controller-351_a_fr](https://cloud.githubusercontent.com/assets/5158475/2740795/264a74d4-c6db-11e3-9290-339e5fc6342f.jpg)

It must use the experimental version Grbl-0.83_1 found in :
https://github.com/LETARTARE/Grbl_with_Arduino/tree/devArduino

Sincerely.

**Comment by zapmaker** [comment]
Yes, this is an idea I had awhile ago such as when you are needing to mill into the side of objects (unreachable with 3-axis only). There are A-axis stepper systems for about $200 US.

What are your thoughts on how this should be handled in Grbl Controller? Should there be a checkbox option to simply change the value from A or C in the user interface? Default to A?

**Comment by LETARTARE** [comment]
Currently Official Grbl-0.8c offers Mega2560 for 3 axes. But he studied the transition to 4 axes Due / Mega. I adapted the old Grbl-0.81 -> 0.83_1, 
 The axis A (around X) is used for a turntable (A-axis stepper systems). 

So it seems appropriate to have A default. 

If requests arrive for the C axis, we can add it again.

You want me to give you this new version?
Sincerely.

**Comment by zapmaker** [comment]
I tried your 0.83_1 with changes I've made to Grbl Controller and it works - I've checked in support for A B or C axis in version 3.6. I have not built any exe's yet as I hope to make further changes soon for other issues. Let me know if you need a Windows build to test with.

One minor issue is that to build 0.83_1 I checked out the branch devArduino, copied the entire repo into the libraries folder, restarted Arduino IDE, opened the ino file for 0.83_1 and there were no other files there, I had to manually add them. Then I had to change #include <main.h> to #include "main.h" to get it to properly compile the ino. After that all was good. My 1.0.5 install is in Program Files (x86), which may be part of the problem.

![a-axis-support](https://cloud.githubusercontent.com/assets/2454235/2749545/3bbbbe2c-c80c-11e3-9dbe-5aeee04e5244.png)

**Comment by zapmaker** [comment]
Another screenshot. If you can test it, let me know if you run into any issues. Thanks!

![a-axis-support-options](https://cloud.githubusercontent.com/assets/2454235/2749548/7ca06f50-c80c-11e3-9b28-69857fc122e3.png)

**Comment by LETARTARE** [comment]
hi roman,
before going to sleep : 
 you must rename the directory "0.83_1" -> "Grbl83Mega" and especially a single directory of grbl in "libraries".
I look at your 3.6 tomorrow.
Bye.

**Comment by LETARTARE** [comment]
i have just tested 3.6 on Vista with 0.83_1 : all right for A.
Can you test 
https://github.com/LETARTARE/Grbl_with_Arduino/tree/master/Grbl84Mega2560

**Comment by zapmaker** [comment]
That one worked very nicely - I didn't have to add any files to the project. Worked on A. I will update my web site to link to this project.

**Comment by zapmaker** [comment]
Closing issue - fixed in 3.6

**Comment by derFrickler** [comment]
Very cool, do you know if this grbl version will allthough work with 4 steppers on a 2-portal styro cutter like this: 
http://i01.i.aliimg.com/photo/v0/103439335/FC2913_Hot_Wire_CNC_Foam_Cutter.jpg
I am planing to build one of these. The GCode would be like G01 X300 Y300 Z340 A240 for moving both portals synchronous to a defined position.

**Comment by zapmaker** [comment]
I'm fairly sure it won't work because the A axis is rotational - the grbl patch is specifically coded to do rotations. Since you are doing two independent linear motions, it may be possible to create a version that will work with these foam cutters with minimal code change.

**Comment by zapmaker** [comment]
But I am almost certain that only grbl code needs to change - Grbl Controller should work fine with such a system.

**Comment by derFrickler** [comment]
Yes, you are right, i will try it out, A Axis is defined as steps/deg but all the movement code just seems to be copied from the other axis. Maybe it is enough if i just give it gcode with mm instead of deg.

**Comment by cxbcxb** [comment]
I need GrblController 3.6. I can't make it. Who can send it to my Email: cxbggo@gmail.com

**Comment by jomeny** [comment]
Where can i get this verion of grbl controller or could someone share it  my email is jomeny67@hotmail.com
