### ISSUE TITLE
Grbl has line-length limits (50 for 0.8c and earlier, 70 for 0.8cDEV and later), round decimals off to meet this limit

### ISSUE THREAD

**Issue by WillAdams** [zapmaker/GrblHoming#6]

**Comment by zapmaker** [comment]
This has been fixed in recently released version 3.4

**Comment by WillAdams** [comment]
Is there some configuration option which needs to be set? I'm getting the weird stair-stepping which this causes when I try to cut my current project.

**Comment by zapmaker** [comment]
Yes, you need to check "Selectively reduce precision for excessively long lines" in Options
